### GET all students
GET http://0.0.0.0:3001/api/student
Content-Type: application/json

###

### GET single student
GET http://0.0.0.0:3001/api/student/1
Content-Type: application/json

###

### POST new student
POST http://0.0.0.0:3001/api/student
Content-Type: application/json

{
  "admissionNumber": "ADM123",
  "name": "John Doe",
  "form": "Form 3",
  "stream": "A",
  "gender": "Male",
  "dateOfBirth": "2008-05-12T00:00:00.000Z",
  "enrollmentDate": "2023-01-15T00:00:00.000Z",
  "kcpeMarks": 400,
  "previousSchool": "Sunrise Primary",
  "parentName": "Jane Doe",
  "parentEmail": "jane.doe@example.com",
  "parentPhone": "0712345678",
  "emergencyContact": "0723456789",
  "address": "123 Main Street, Nairobi",
  "medicalInfo": "None",
  "hobbies": "Football, Chess",
  "academicPerformance": "Excellent",
  "attendance": "Good",
  "disciplineRecord": "Clean",
  "status": "Active"
}

###

### PUT update student
PUT http://0.0.0.0:3001/api/student/1
Content-Type: application/json

{
  "admissionNumber": "ADM1234",
  "name": "John Doe Updated",
  "form": "Form 4",
  "stream": "B",
  "gender": "Male",
  "dateOfBirth": "2008-05-12T00:00:00.000Z",
  "enrollmentDate": "2023-01-15T00:00:00.000Z",
  "kcpeMarks": 420,
  "previousSchool": "Sunrise Primary",
  "parentName": "Jane Doe",
  "parentEmail": "jane.doe@example.com",
  "parentPhone": "0712345678",
  "emergencyContact": "0723456789",
  "address": "123 Main Street, Nairobi",
  "medicalInfo": "None",
  "hobbies": "Football, Chess",
  "academicPerformance": "Excellent",
  "attendance": "Good",
  "disciplineRecord": "Clean",
  "status": "Active"
}

###

### DELETE student
DELETE http://0.0.0.0:3001/api/student/1
Content-Type: application/json
