##########
@baseUrl = http://0.0.0.0:3001
@contentType = application/json

##########
@baseUrl = http://0.0.0.0:3001
@contentType = application/json

############################################
### 1️⃣ TEST: Create Admin (Emmanuel Makau)
############################################
POST {{baseUrl}}/api/register
Content-Type: {{contentType}}

{
  "name": "Emmanuel Makau",
  "email": "emmanuelmakau90@gmail.com",
  "password": "StrongPass123",
  "phone": "0793472960",
  "role": "ADMIN"
}

###

############################################
### 2️⃣ TEST: Create Teacher (Grace Wambui)
############################################
POST {{baseUrl}}/api/register
Content-Type: {{contentType}}

{
  "name": "Grace Wambui",
  "email": "gracewambui@example.com",
  "password": "TeacherPass01",
  "phone": "0712345678",
  "role": "TEACHER"
}

###

############################################
### 3️⃣ TEST: Create Principal (John Kiprono)
############################################
POST {{baseUrl}}/api/register
Content-Type: {{contentType}}

{
  "name": "John Kiprono",
  "email": "johnkiprono@example.com",
  "password": "Principal2024",
  "phone": "0789123456",
  "role": "PRINCIPAL"
}

###

############################################
### GET all users
############################################
GET {{baseUrl}}/api/student
Content-Type: {{contentType}}

###
